---
title: "Twitter Untersuchung PE 2.0"
output:
  github_document:
    toc: yes
    toc_depth: 4
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_depth: 4
Author: Benjamin Meisenbichler
---



```{r load packages}
library(readxl)
library(dplyr)
library(xlsx)
library(tidyverse)
```

```{r loadfile-de}
pers_de <- read_excel(
        "../Data/Pers.xlsx",
        sheet = 1,
        col_names = TRUE,
        col_types = NULL,
        na = "",
        skip = 0
        )
set.seed(123)
pers_de_sample <- sample_n(pers_de, 115)
saveRDS(pers_de, file = "../Data/pers_de.rds")

```
```{r write-table, eval=FALSE}
write.xlsx(x = pers_de_sample, file = "../Data/pers_sample.xlsx",
           sheetName = "DE", col.names = TRUE, showNA = TRUE, append = TRUE)
write.xlsx(x = pers_at_sample, file = "../Data/pers_sample.xlsx",
           sheetName = "AT", col.names = TRUE, showNA = TRUE, append = TRUE)
write.xlsx(x = pers_ch_sample, file = "../Data/pers_sample.xlsx",
           sheetName = "CH", col.names = TRUE, showNA = TRUE, append = TRUE)
```


```{r loadfile-at}
pers_at <- read_excel(
        "../Data/Pers.xlsx",
        sheet = 2,
        col_names = TRUE,
        col_types = NULL,
        na = "",
        skip = 0
        )
set.seed(456)
pers_at_sample <- sample_n(pers_at, 83)
saveRDS(pers_at, file = "../Data/pers_at.rds")

```

```{r loadfile-ch}
pers_ch <- read_excel(
        "../Data/Pers.xlsx",
        sheet = 3,
        col_names = TRUE,
        col_types = NULL,
        na = "",
        skip = 0
        )
set.seed(789)
pers_ch_sample <- sample_n(pers_ch, 33)
saveRDS(pers_ch, file = "../Data/pers_ch.rds")

```

# Test

*Test*
